[[headers]]
for = "/*"
  [headers.values]
  X-Robots-Tag = "noindex, nofollow"

[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200